stages:
  - stage: Continuosintegration
    DisplayName: Continuosintegration
    jobs:
    - job: dotnetbuild
      displayName: dotnetbuildjob
      steps:
      - script: dotnet restore
        DisplayName: restore
      - script: dotnet build
        DisplayName: build
      - script: dotnet test
        DisplayName: test
      - script: dotnet publish
        DisplayName: publish artifact